# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "google-cloud-bigquery", "~> 1.23.0"
gem "googleauth", "~> 0.14.0"
